plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/MethodLength:
  Max: 15

Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: false

Rspec/NestedGroups:
  Max: 5

RSpec/VariableName:
  Exclude:
    - 'spec/requests/**/*_spec.rb'

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/requests/**/*_spec.rb'