{
  "openapi": "3.0.1",
  "info": {
    "title": "Exchange Rate Provider API",
    "version": "v1",
    "description": "API for retrieving exchange rates."
  },
  "servers": [
    {
      "url": "{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "http://localhost:3000"
        }
      }
    }
  ],
  "paths": {
    "/api/v1/exchange_rates": {
      "get": {
        "summary": "Lists exchange rates",
        "tags": [
          "Exchange Rates"
        ],
        "description": "Retrieves exchange rates based on source currency",
        "parameters": [
          {
            "name": "source_currency",
            "in": "query",
            "required": true,
            "schema": {
              "pattern": "^[A-Z]{3}$",
              "default": "CZK"
            }
          },
          {
            "name": "date",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "format": "date"
            }
          },
          {
            "name": "target_currency[]",
            "in": "query",
            "required": false,
            "schema": {
              "type": "array",
              "items": {
                "type": "string",
                "pattern": "^[A-Z]{3}$"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "examples": {
                  "with basic parameters OK returns a 200 response": {
                    "value": {
                      "source_currency": "CZK",
                      "rates": {
                        "AUD": {
                          "amount": 1.0,
                          "rate": 14.001
                        },
                        "BRL": {
                          "amount": 1.0,
                          "rate": 3.904
                        },
                        "BGN": {
                          "amount": 1.0,
                          "rate": 12.747
                        },
                        "CNY": {
                          "amount": 1.0,
                          "rate": 3.015
                        },
                        "DKK": {
                          "amount": 1.0,
                          "rate": 3.34
                        },
                        "EUR": {
                          "amount": 1.0,
                          "rate": 24.93
                        },
                        "PHP": {
                          "amount": 100.0,
                          "rate": 39.21
                        },
                        "HKD": {
                          "amount": 1.0,
                          "rate": 2.824
                        },
                        "INR": {
                          "amount": 100.0,
                          "rate": 25.91
                        },
                        "IDR": {
                          "amount": 1000.0,
                          "rate": 1.32
                        },
                        "ISK": {
                          "amount": 100.0,
                          "rate": 17.087
                        },
                        "ILS": {
                          "amount": 1.0,
                          "rate": 6.033
                        },
                        "JPY": {
                          "amount": 100.0,
                          "rate": 15.329
                        },
                        "ZAR": {
                          "amount": 1.0,
                          "rate": 1.179
                        },
                        "CAD": {
                          "amount": 1.0,
                          "rate": 15.843
                        },
                        "KRW": {
                          "amount": 100.0,
                          "rate": 1.54
                        },
                        "HUF": {
                          "amount": 100.0,
                          "rate": 6.168
                        },
                        "MYR": {
                          "amount": 1.0,
                          "rate": 5.076
                        },
                        "MXN": {
                          "amount": 1.0,
                          "rate": 1.121
                        },
                        "XDR": {
                          "amount": 1.0,
                          "rate": 29.727
                        },
                        "NOK": {
                          "amount": 1.0,
                          "rate": 2.112
                        },
                        "NZD": {
                          "amount": 1.0,
                          "rate": 12.966
                        },
                        "PLN": {
                          "amount": 1.0,
                          "rate": 5.834
                        },
                        "RON": {
                          "amount": 1.0,
                          "rate": 5.007
                        },
                        "SGD": {
                          "amount": 1.0,
                          "rate": 16.772
                        },
                        "SEK": {
                          "amount": 1.0,
                          "rate": 2.272
                        },
                        "CHF": {
                          "amount": 1.0,
                          "rate": 26.559
                        },
                        "THB": {
                          "amount": 100.0,
                          "rate": 65.535
                        },
                        "TRY": {
                          "amount": 100.0,
                          "rate": 56.938
                        },
                        "USD": {
                          "amount": 1.0,
                          "rate": 21.905
                        },
                        "GBP": {
                          "amount": 1.0,
                          "rate": 29.266
                        }
                      }
                    }
                  },
                  "with target currency filter OK returns a 200 response": {
                    "value": {
                      "source_currency": "CZK",
                      "rates": {
                        "EUR": {
                          "amount": 1.0,
                          "rate": 24.93
                        },
                        "USD": {
                          "amount": 1.0,
                          "rate": 21.905
                        }
                      }
                    }
                  },
                  "with date parameter OK returns a 200 response": {
                    "value": {
                      "source_currency": "CZK",
                      "rates": {
                        "AUD": {
                          "amount": 1.0,
                          "rate": 14.715
                        },
                        "BRL": {
                          "amount": 1.0,
                          "rate": 3.983
                        },
                        "BGN": {
                          "amount": 1.0,
                          "rate": 12.814
                        },
                        "CNY": {
                          "amount": 1.0,
                          "rate": 3.227
                        },
                        "DKK": {
                          "amount": 1.0,
                          "rate": 3.363
                        },
                        "EUR": {
                          "amount": 1.0,
                          "rate": 25.085
                        },
                        "PHP": {
                          "amount": 100.0,
                          "rate": 40.833
                        },
                        "HKD": {
                          "amount": 1.0,
                          "rate": 3.016
                        },
                        "INR": {
                          "amount": 100.0,
                          "rate": 26.928
                        },
                        "IDR": {
                          "amount": 1000.0,
                          "rate": 1.437
                        },
                        "ISK": {
                          "amount": 100.0,
                          "rate": 17.123
                        },
                        "ILS": {
                          "amount": 1.0,
                          "rate": 6.464
                        },
                        "JPY": {
                          "amount": 100.0,
                          "rate": 15.662
                        },
                        "ZAR": {
                          "amount": 1.0,
                          "rate": 1.269
                        },
                        "CAD": {
                          "amount": 1.0,
                          "rate": 16.277
                        },
                        "KRW": {
                          "amount": 100.0,
                          "rate": 1.616
                        },
                        "HUF": {
                          "amount": 100.0,
                          "rate": 6.29
                        },
                        "MYR": {
                          "amount": 1.0,
                          "rate": 5.292
                        },
                        "MXN": {
                          "amount": 1.0,
                          "rate": 1.14
                        },
                        "XDR": {
                          "amount": 1.0,
                          "rate": 30.878
                        },
                        "NOK": {
                          "amount": 1.0,
                          "rate": 2.124
                        },
                        "NZD": {
                          "amount": 1.0,
                          "rate": 13.31
                        },
                        "PLN": {
                          "amount": 1.0,
                          "rate": 6.037
                        },
                        "RON": {
                          "amount": 1.0,
                          "rate": 5.041
                        },
                        "SGD": {
                          "amount": 1.0,
                          "rate": 17.526
                        },
                        "SEK": {
                          "amount": 1.0,
                          "rate": 2.278
                        },
                        "CHF": {
                          "amount": 1.0,
                          "rate": 26.341
                        },
                        "THB": {
                          "amount": 100.0,
                          "rate": 69.661
                        },
                        "TRY": {
                          "amount": 100.0,
                          "rate": 64.322
                        },
                        "USD": {
                          "amount": 1.0,
                          "rate": 23.44
                        },
                        "GBP": {
                          "amount": 1.0,
                          "rate": 30.02
                        }
                      }
                    }
                  },
                  "with unsupported source currency OK returns a 200 response": {
                    "value": {}
                  }
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Content",
            "content": {
              "application/json": {
                "examples": {
                  "with invalid source currency format Unprocessable Content returns a 422 response": {
                    "value": {
                      "errors": {
                        "source_currency": [
                          "is in invalid format"
                        ]
                      }
                    }
                  },
                  "with invalid target currency format Unprocessable Content returns a 422 response": {
                    "value": {
                      "errors": {
                        "target_currency": {
                          "0": [
                            "is in invalid format"
                          ]
                        }
                      }
                    }
                  },
                  "with invalid date format Unprocessable Content returns a 422 response": {
                    "value": {
                      "errors": {
                        "date": [
                          "is in invalid format"
                        ]
                      }
                    }
                  },
                  "when external server returns an error Unprocessable Content returns a 422 response": {
                    "value": {
                      "errors": {
                        "base": [
                          "API request failed with status 400"
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}