name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Check code style with RuboCop
        run: bundle exec rubocop

      - name: Scan for Rails security vulnerabilities
        run: bin/brakeman --no-pager
        
      - name: Run tests
        run: bundle exec rspec
